---
title: "Maps and CO Demographics"
author: "Theodore Dounias"
date: "September 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(knitr)
library(plotly)
library(maps)
opts_knit$set(root.dir = 'C:/Users/tdounias/Desktop/Reed College/2017 Fall/MATH 243/Repos/Reed_Senior_Thesis/Data_and_results/')
```

#My First Map
```{r}
col <- map_data("county") %>%
  filter(region == 'colorado')

county_registrants <- vrf %>%
  mutate(count = 1) %>%
  group_by(COUNTY) %>%
  summarise(TOTAL_REGISTERED = sum(count))

county_registrants$COUNTY <- tolower(county_registrants$COUNTY) # matching string

col_reg <- merge(col, county_registrants, by.x = "subregion", by.y = "COUNTY")

col_reg$pop_cat <- cut(col_reg$TOTAL_REGISTERED, breaks = c(seq(0, 500000, by = 100000)), labels=1:5)

p <- col_reg %>%
  group_by(group) %>%
  plot_ly(x = ~long, y = ~lat, color = ~pop_cat, colors = c('pink', 'dark red'),
          text = ~subregion, hoverinfo = 'text') %>%
  add_polygons(line = list(width = 0.4)) %>%
  add_polygons(
    fillcolor = 'transparent',
    line = list(color = 'black', width = 0.5),
    showlegend = FALSE, hoverinfo = 'none'
  ) %>%
  layout(
    title = "Colorado Total Registrants by County",
    titlefont = list(size = 10),
    xaxis = list(title = "", showgrid = FALSE,
                 zeroline = FALSE, showticklabels = FALSE),
    yaxis = list(title = "", showgrid = FALSE,
                 zeroline = FALSE, showticklabels = FALSE)
  )

p
```

