---
title: "County Model First Draft"
author: "Theodore Dounias"
date: "10/23/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(Matrix)
library(lme4)
library(gam)
source("~/Desktop/Reed_Senior_Thesis/riggd/R/utils.R")
```

This section includes the two county level models and their coefficients. (Model 1, 2)

```{r county-indiv}
setwd("~/Desktop/Reed_Senior_Thesis/Data_and_results/data")
model_sample <- read_csv("model_indiv_sample.csv")
demographics <- read_csv("colorado_demographic_stats_by_county.csv")



#Run the models
md_1 <- glmer(family = "binomial", data = model_sample, 
              voted ~ (1|COUNTY))

arm::display(md_1)

md_2 <- glmer(family = "binomial", data = model_sample, 
              voted ~ (1|COUNTY) + PCT_URBAN + PCT_WHITE)

#Display results
arm::display(md_2)

#Fixed effects
fixef(md_2)

#########################
##Diagnostics and Plots##
#########################

##12.6 Graphs
county_coefs <- coef(md_2)[[1]][,1]

plot_data <- data.frame(cbind(county_coefs, demographics$PCT_URBAN, demographics$PCT_WHITE), ranef(md_2)[[1]][,1])

names(plot_data) <- c("estimated_coefs", "urban", "white", "coef_se")

##Urban pop graph (12.6)
ggplot(plot_data, aes(x = urban, y = estimated_coefs)) +
  geom_pointrange(aes(ymin= estimated_coefs-coef_se, ymax=estimated_coefs+coef_se), size = .1) +
  geom_abline(slope = fixef(md_2)[2], intercept = fixef(md_2)[1])

##White pop graph (12.6)
ggplot(plot_data, aes(x = white, y = estimated_coefs)) +
  geom_pointrange(aes(ymin= estimated_coefs-coef_se, ymax=estimated_coefs+coef_se), size = .1) +
  geom_abline(slope = fixef(md_2)[3], intercept = fixef(md_2)[1])
```


The calls for models 3 and 3a:

```{r id and county mixedeff}
md_3 <- glmer(family = "binomial", data = model_sample, 
             voted ~ PCT_URBAN + PCT_WHITE + GENDER + (1|COUNTY) + (1|VOTER_ID))

md_3a <- glmer(family = "binomial", data = model_sample, 
              voted ~ PCT_URBAN + PCT_WHITE + GENDER + (1|COUNTY))

summary(md_3)

summary(md_3a)
```

The calls for model 4:

```{r election effects}
md_4 <- gam(family = "binomial", data = model_sample, 
            voted ~ ns(ELECTION_DATE) + ELECTION_TYPE)

summary.gam(md_4)
```

The calls for model 5, 5a:

```{r}
model_sample$ELECTION_DATE <- (year(model_sample$ELECTION_DATE))
model_sample$AGE <- scale(model_sample$AGE)

md5 <- glm(data = model_sample, family= "binomial", 
           voted ~ AGE + PARTY + MAIL_VOTE)

summary(md5)

md5a <- glmer(data = model_sample, family= "binomial", 
              voted ~ AGE + PARTY + MAIL_VOTE + (1|COUNTY) +
                PCT_WHITE + PCT_URBAN + GENDER)

summary(md5a)
```

#CV AUC

```{r}
#Get folds from data
set.seed(1)
folds <- split(sample(nrow(model_sample), nrow(model_sample),replace=FALSE), as.factor(1:5))

get_true <- function(probs){
  a <- rep(0, length(probs))
  a <- data.frame(ifelse(probs >= .5, 1, 0))
  names(a) <- "probs"
  a
}

#Model 1
auc_1 <- rep(0,5)

for(i in 1:5){
  md_1.fit <- glmer(family = "binomial", data = model_sample, 
                voted ~ (1|COUNTY), subset = -folds[[i]])

  prob <- predict(md_1.fit, model_sample, type = "response")[folds[[i]]]
  
  temp_data <- data.frame(prob, model_sample$voted[folds[[i]]])
  names(temp_data) <- c("prob", "voted")

  g <- roc(voted ~ prob, data = temp_data)
  plot(g)   
  auc_1[i] <- auc(g)
}

mean(auc_1)

#Model 2
auc_2 <- rep(0,5)

for(i in 1:5){
  md_2.fit <- glmer(family = "binomial", data = model_sample, 
                    voted ~ (1|COUNTY) + PCT_WHITE + PCT_URBAN, 
                    subset = -folds[[i]])
  
  prob <- predict(md_2.fit, model_sample, type = "response")[folds[[i]]]
  
  temp_data <- data.frame(prob, model_sample$voted[folds[[i]]])
  names(temp_data) <- c("prob", "voted")
  
  g <- roc(voted ~ prob, data = temp_data)
  plot(g)   
  auc_2[i] <- auc(g)
}

mean(auc_2)

#Model 3
# auc_3 <- rep(0,5)
# 
# for(i in 1:5){
#   md_3.fit <- glmer(family = "binomial", data = model_sample, 
#                voted ~ PCT_URBAN + PCT_WHITE + GENDER + (1|COUNTY) + (1|VOTER_ID),
#                subset = -folds[[i]])
#   
#   prob <- predict(md_3.fit, model_sample, type = "response")[folds[[i]]]
#   
#   temp_data <- data.frame(prob, model_sample$voted[folds[[i]]])
#   names(temp_data) <- c("prob", "voted")
#   
#   g <- roc(voted ~ prob, data = temp_data)
#   plot(g)   
#   auc_3[i] <- auc(g)
#}

#Model 3a
auc_3a <- rep(0,5)

for(i in 1:5){
  md_3a.fit <- glmer(family = "binomial", data = model_sample, 
                 voted ~ PCT_URBAN + PCT_WHITE + GENDER + (1|COUNTY),
                 subset = -folds[[i]])
  
  prob <- predict(md_3a.fit, model_sample, type = "response")[folds[[i]]]
  
  temp_data <- data.frame(prob, model_sample$voted[folds[[i]]])
  names(temp_data) <- c("prob", "voted")
  
  g <- roc(voted ~ prob, data = temp_data)
  plot(g)   
  auc_3a[i] <- auc(g)
}

mean(auc_3a)

#Model 4
auc_4 <- rep(0,5)

for(i in 1:5){
  md_4.fit <- gam(family = "binomial", data = model_sample, 
              voted ~ ns(ELECTION_DATE) + ELECTION_TYPE, 
              subset = -folds[[i]])
  
  prob <- predict(md_4.fit, model_sample, type = "response")[folds[[i]]]
  
  temp_data <- data.frame(prob, model_sample$voted[folds[[i]]])
  names(temp_data) <- c("prob", "voted")
  
  g <- roc(voted ~ prob, data = temp_data)
  plot(g)   
  auc_4[i] <- auc(g)
}

mean(auc_4)

#Model 5
auc_5 <- rep(0,5)

for(i in 1:5){
  md_5.fit <- glm(data = model_sample, family= "binomial", 
             voted ~ AGE + PARTY + MAIL_VOTE, subset = -folds[[i]])

  prob <- predict(md_5.fit, model_sample, type = "response")[folds[[i]]]
  
  temp_data <- data.frame(prob, model_sample$voted[folds[[i]]])
  names(temp_data) <- c("prob", "voted")
  
  g <- roc(voted ~ prob, data = temp_data)
  plot(g)   
  auc_5[i] <- auc(g)
}

mean(auc_5)

#Model 5a
auc_5a <- rep(0,5)

for(i in 1:5){
  md_5a.fit <- glmer(data = model_sample, family= "binomial", 
                voted ~ AGE + PARTY + MAIL_VOTE + (1|COUNTY) +
                  PCT_WHITE + PCT_URBAN + GENDER, subset = -folds[[i]])
  
  prob <- predict(md_5a.fit, model_sample, type = "response")[folds[[i]]]
  
  temp_data <- data.frame(prob, model_sample$voted[folds[[i]]])
  names(temp_data) <- c("prob", "voted")
  
  g <- roc(voted ~ prob, data = temp_data)
  plot(g)   
  auc_5a[i] <- auc(g)
}

mean(auc_5a)
```

