<!-- The {.unnumbered} option here means that the introduction will be "Chapter 0." -->

# Introduction {.unnumbered}

Elections shift the course of history in ways that are sometimes small, but often enormous. Particularly in the United States, but really in any democracy across the world, elections have the capacity to shape the existence of millions of people for decades to come. Elections are written in the history books, regardless of the final outcome. It is truly wondrous that this power is in *our* hands, that every seismic shift in the course of our states comes from the tremors each of us cause with our ballots. This is a power that people have suffered and continue to suffer for, a power my own parents and grandparents risked their lives for. The way we give people access to this power, the way nations like the United States or my birthplace of Greece choose to conduct their elections and the enfranchisement and disenfranchisement such choices may cause has never ceased to be contentious.  
  
What quickly becomes apparent is that beyond the soaring rhetoric of democratic power, the setup of our elections systems is not straightforward in the slightest. Starting from the beginning, there is still no consensus on *who* gets to vote. Do felons get the vote? Florida (as of 2018) says yes, as does much of Europe, but other states in the US say no. How about permanent residents? Should people have to pass a basic political knowledge test to vote? Is one informed vote more important than a vote from someone who lacks knowledge of current affairs and government? Should people be forced to show ID when voting, or is this restrictive and undemocratic? *When* people get to vote is similarly contentious. Is early voting something we should support, or does it dilute the effect of election day turnout? Should voting day be a national holiday? How about refferenda? Should the people be directly consulted by their governments on seminal issues? Finally, there is the question of *how* or *where* people vote. How many polling places are enough? Should we use paper ballots or voting machines? Should people be automatically registered to vote? Should they be allowed to register on election day? Do we freeze registrations before election day, and if so how long before? Should we allow voting by mail? Permanent absentee status? All-mail elections? This is all even before making choices on subjects like the allocation of representatives by state or prefecture, or the total number of parliamentarians, or how many chambers congress should have.

The 2000 Presidential election between Al Gore and George W. Bush was decided in Florida by a razor thin margin of ballots. Following the final result, which occurred in the halls of the United States Supreme Court whose decision in *Bush v. Gore* halted all Florida recounts that were in progress, researchers claimed that the voting machines and ballot cards used were confusing and misleading. Many voters, for example, mistakenly voted for a different candidate because of the confusing layout of outdated punch-card voting machines[@wand_butterfly_2001]. 22,000 voters in Duval County had their ballots rejected due to "over-voting", because they were given ballots that implied the necessity to vote on multiple pages for the same candidate: an action that spoiled their ballot[@saltman_history_2009].

A democratic system is based on procedures as much as on principles. Elections are about translating the vote of the people into political power, government action, and fair representation by chosen representatives. The way we vote can often be critical to the outcome. Thus the design and implementation of voting systems is far from being neutral; the decisions made on who votes, and how, when, and where they do so often serves to alter the course of history. Underlying those decisions is a nebulous, inconclusively answered question: are elections fair, and how can we make them more so?

The United States has long grappled with translating this goal into policy. During the Civil War, several states like Virginia pioneered the use of absentee mail ballots to serve military personnel and displaced residents; this same policy was expanded nationwide in 1942, to accommodate for soldiers and factory workers serving US efforts in World War II. In 1871 Congress passed the Enforcement Act, which clearly defined acts like voter impersonation or intimidation as crimes, and set up a clear, federal structure of supervisors and marshals tasked with overseeing all elections. This was the first in what was to become over a century of sweeping federal election reforms, in an attempt to at least partially centralize an election process whose control had been left to localities. The Civil Rights Acts of '57, '60, and '64 along with the Voting Rights Act of '65 collectively aimed to prevent discriminatory policies at the local level. They abolished literacy tests, made tampering with voter registration rolls a federal crime, and mandated federal oversight of local authorities with a history of discriminatory voter registration practices.   
  
In 1993 Congress passed the National Voter Registration Act (or NVRA), which increased oversight of local registration policies by mandating by-mail registration and registration at the DMV (otherwise known as the "motor voter" program), and by strictly regulating local registration forms. The NVRA also imposed strict regulations against the practice of "purging" registered voters from the rolls, and mandated that states routinely check their registration data to ensure integrity. After the events of 2000 in Florida, the NVRA was followed by the Help America Vote Act (HAVA) of 2002. HAVA included sweeping changes to how American election administration was conducted. For the first time in history, the federal government started spending money on local election administration. The act also banned certain types of voting machines, mandated that local officials accept provisional ballots, and created the Elections Administration Commission (EAC) to gather information and assist state and national elections. Quite importantly for researchers and voters alike (and for this thesis), HAVA mandated that states compile and maintain voter registration and history data *at the state level*, providing some centralized oversight for elections[@ewald_way_2009].
  
Apart from serving local election administration, voter files consolidated by HAVA have allowed researchers to make concrete inferences of individual characteristics [@hersh_hacking_2015]. Voting related theories derived from political science are now commonly tested using advanced statistical methods and huge amounts of data; both disciplines tackle these data to face joint problems such as quantifying the quality of voter registration files [@ansolabehere_quality_2010], or linking disparate voter records [@ansolabehere_adgn:_2017]. In my thesis I take advantage of such centralized files from the state of Colorado^[Voter files commonly include two distinct parts: Voter Registration Files (VRF) and Voter History Files. The former contain an entry for each registered individual with all necessary demographic and personal data needed to correctly identify which ballots they should complete, like where they live, their party registration, their local legislative district, precinct, school board etc. The later contain information on each *ballot* cast, including who cast it, what election it was cast in, how it was cast (mail vote, absentee, etc.), and what county it was cast in.].
  
The purpose of research into policies like the ones described above is to both to model and understand the behavior of the voters, and to formulate an idea on what the optimal policy is. Research conclusions on their own obviously cannot sway policy; such decisions are made, fittingly, with the input of the people or their representatives through processes of policy-making, whose study and function is beyond the scope of this thesis. In my thesis, I wish to focus on just one of the multitude of elections policies that are either discussed or enacted in the US at present: Vote By Mail. My purpose is to add to the existing literature of quantitative studies on how Vote By Mail affects voter turnout, and through this process draw conclusions on what behavioral model of voter choice best fits the reality of mail voting.

Apart from the data, such research is also dependent on the statistical methods used to draw inferences. In my thesis, I construct both county- and individual-level models of turnout by using methods such as logistic regression, hierarchical modelling, and natural splines. The use of hierarchical modelling here is particularly significant, as the vast majority of previous studies on mail voting have employed fixed effects models. Hierarchical modelling is particularly salient when data exhibit different "levels" of grouping, here represented by the counties in which individual voters are registered. While fixed-effects regression would assume independence of effects between counties, hierarchical modeling will allow me to do away with that assumption, thus also vastly increasing the inferential potential of my models[@gelman_data_2006].

This thesis should be viewed as a combination of three factors: questions, data, and methods. My fundamental question is one of the most common for elections science^[Sometimes referred to as *psephology*, the study of the *psephos* ($\psi \acute \eta \phi o \varsigma$) or "vote" in Greek.]: how do we increase electoral participation in the form of turnout, and consequently how do voters choose when to vote? My data comes from Colorado Voter Registration Files: a complete, all-inclusive collection of all current registrants in the State along with their voter histories. To these data, with the purpose of answering the fundamental question I set, I apply hierarchical models; a practice commonly applied in statistical studies but relatively new and exciting as a development in mail voting research.