---
output: pdf_document
---

# Conclusion {.unnumbered}
  \setcounter{chapter}{5}
	\setcounter{section}{0}

At the end of my thesis I am able to confirm H1, but reject H2 and H3. These results come from my County level models. Despite non-convergence my individual level models have some inferential potential, but they are still not particularly useful at testing my hypotheses on VBM. This is true because of the variability concerns outlined early in Chapter 4. I confirm H1 because mail voting seems to be an incremental, comparably small effect on turnout. I reject H2/H3 because that effect is not more pronounced for elections that have less strong national influences. In fact, my county-level models showed the exact opposite: VBM had a strong, significant positive effect for midterm and presidential elections, but no discernible effect for primary or coordinated races. 

This is evidence against voting "at the margins", since my hypotheses that were most connected to Aldrich's paradigm (H2, H3) were convincingly rejected. I find evidence against a hypothesis of habitual voting as well, since in my county models Mail Voting has a significant, positive effect. This means that the absence of election-day effects or the strong presence of habitual voting did not override the effect on turnout that mail voting has. The same conclusion can be drawn for a social theory of voting, which predicts no effect.

The best way to interpret my results is through a resources and organizational lens, since this theory predicts a consistent, positive effect of VBM on turnout because of the increase in capacity it gives to individuals. In the trade-off between voting and not voting, whether casting a ballot consumes time and effort seems to have had the largest impact, which is why my models show such an effect. However, it should be noted that this effect should be present in *all* elections to be convincing evidence for the resources electoral participation paradigm. This is not the case. One explanation may be that my models were sensitive to the vastly greater turnout that occurs during presidential and midterm years, particularly since the differences in mail voting percentage between counties was at most around 20%. This, again, leads to the conclusion that the lack of variability in my data does not permit any more precise analysis.

The first step towards future research, directly resulting from this problem, would be to get more data. This is very possible, but a task I was unable to accomplish due to time constraints related to this project. More data would allow for a comparative study of Colorado elections before and after all major legislative electoral changes of this century (2008, 2013). Another way to expand on my research would be to look at even lower level elections, like municipal elections, school board elections, or recall elections; voter history files contain data on all of these races. A study with more data could use such races as well for testing the hypotheses I set up in this thesis. Third, it is possible to replicate my research here for other states like Oregon and Washington, or for the specific counties in Arizona, Utah, or California that have all-mail elections. Fourth, elections thankfully do not stop happening; my research here can always be updated with data from the 2017 Coordinated Colorado election, or the 2018 Midterm that just took place. I would caution that the same issue with data variability would still exist in this case; there is a much greater need for data going back, rather than new all-mail elections. 

Apart from expanding my research in terms of data, another path would be to impliment some of the methods I outline in the beginning of Chapter 4, like the Synthetic Control Group. Such methods would allow for inferences to be made despite the data issues I encountered. Lastly, it should be noted that VBM is just one of a series of electoral reforms like Automatic Voter Registration (AVR), Early Voting, or Voter ID Restrictions, all of which can potentially be tested using multilevel models and data wrangling methods that I have applied in this thesis. 
  
Another contribution of my thesis is my analysis of data wrangling, the construction of multilevel general additive models for turnout, and the accompanying \textit{R} package. To take these one by one, I have provided arguments in favor of preferring multiple snapshots of registration files rather than just the latest iteration of the record. I have analyzed the pitfalls that exist in such documents, and given specific examples on how this can be dealt with for the Colorado data files. I have also provided a set of variable specification that can be useful as indicators of the content of these data, or the potential uses of voter registration files in other future studies. Finally, I have presented potential future solutions to issues these data have with variability, and ways to circumvent processing power limitations.
   
Additionally, I have meticulously gone through the creation of multilevel general additive models of individual and county level turnout. While due to data and processing power limitations I am unable to run all these models to typical standards of convergence. This does not mean that they present no value to future research. Quite the contrary, future researchers just have to go through the data clean-up stage, and then implement my models without having to construct them from scratch. In particular, mixed effects and general additive models are not widely used in such studies, making their presentation and specification rather unique regardless of their application in this piece of research.  
  
Lastly, I provide an extensive library of code used to create this document and the research I conduct. I have made an \textit{R} package--which I named `riggd`--that includes more than a dozen different functions that serve data wrangling and presentation purposes. These functions are made for use on Colorado files, but require relatively small amounts of changes to be applied to voter files from around the US. I also provide code for all tables and graphics that are included in this thesis on gitHub, which is a testament to the reproducibility and future value of the research I conducted.  

I recognize that, despite many obstacles in terms of data or computing power, the outcome of this thesis being more constructive rather than conclusive is to some extent my fault. There were many problems in this thesis that I should have been aware of earlier in the process, which may have allowed me to present more concrete results rather than a series of tools and methods. However, in the combination of my existing conclusions and the materials I have created through this process, it is my belief that this thesis does in fact present a step forward in the literature, and that it adds to existing quantitative elections studies works. This is a small step, but it helps in our understanding of how voters behave, what the actual results of election policy are, and how to expand participation.

<!--
If you feel it necessary to include an appendix, it goes here.
-->

\appendix

